USE [master]
GO

/****** Object:  Database [prj301-take-attendence]    Script Date: 19/04/2022 1:10:36 pm ******/
CREATE DATABASE [prj301-take-attendence]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'prj301-take-attendence', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\prj301-take-attendence.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'prj301-take-attendence_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\prj301-take-attendence_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [prj301-take-attendence].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [prj301-take-attendence] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET ARITHABORT OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [prj301-take-attendence] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [prj301-take-attendence] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET  DISABLE_BROKER 
GO

ALTER DATABASE [prj301-take-attendence] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [prj301-take-attendence] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET RECOVERY FULL 
GO

ALTER DATABASE [prj301-take-attendence] SET  MULTI_USER 
GO

ALTER DATABASE [prj301-take-attendence] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [prj301-take-attendence] SET DB_CHAINING OFF 
GO

ALTER DATABASE [prj301-take-attendence] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [prj301-take-attendence] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [prj301-take-attendence] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [prj301-take-attendence] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [prj301-take-attendence] SET QUERY_STORE = OFF
GO

ALTER DATABASE [prj301-take-attendence] SET  READ_WRITE 
GO

